### ISSUE TITLE
User Profile Images are not shown --> Home / My profile

### ISSUE THREAD

**Issue by Markus-Becker** [silop4all/aod#5]
The image off the user profile is not shown after I added a profile Image to my user Account MarkusBecker. In the html img tag the attribute value src doesn't contain the path to the image instead is the title of the app logo used to build the path.
![image](https://cloud.githubusercontent.com/assets/18029124/23366739/26f347ce-fd08-11e6-9956-286d9899409b.png)

**Comment by silop4all** [comment]
@Markus-Becker A conflict was existing among the application logo and the user logo. It has fixed in the commit d6d0f7ad943145be689e91be4e801b30f0b68549.

**Comment by Markus-Becker** [comment]
It does not work! I get a 404 because the resource is not available after I uploaded it:
http://aod.lifetool.at/media/app/users/logos/11.png

**Comment by silop4all** [comment]
@Markus-Becker Since the github does not allow to commit empty folders, the /media/app/users/logos path did not exist. I added a readme file on it, and I did the commit https://github.com/silop4all/aod/commit/01e6032fab47ada3efc265012701bf1d778723bc.
Do not forget to change the permissions and the owner (www-data:www-data) on this folder in your deployment.

**Comment by Markus-Becker** [comment]
MB: It works (saving a picture for the users account).
