### ISSUE TITLE
In the overview the star rating is above the get it button

### ISSUE THREAD

**Issue by LifetoolAD** [silop4all/aod#6]
I created a test program and in the overview of the homepage the star rating overlaps with the button.

![starratingabovebutton](https://cloud.githubusercontent.com/assets/10863179/22640866/b094ff46-ec54-11e6-8d59-8a80e99134b8.jpg)

**Comment by silop4all** [comment]
@LifetoolAD  The title of the service has been resized (h4->h6). In case that the title is a long string, split it. Change position in the button. 

Check  commit: 32a28ef898a29c881daa19dca63080bebc0cd284.

**Comment by Markus-Becker** [comment]
I put the link behind the paragraph because it looks better.
Bevore:
![image](https://cloud.githubusercontent.com/assets/18029124/23268860/2a8429ba-f9ef-11e6-9bae-0a4951204526.png)

After:
![image](https://cloud.githubusercontent.com/assets/18029124/23268832/148ce2d2-f9ef-11e6-9112-fe1b68b4371d.png)

**Comment by Markus-Becker** [comment]
It works!
